package org.coffer.coffer2.application

object IssuerCodeMapper {

    private val NUMISTA_TO_ISO = mapOf(
        // Alternative language spellings
        "australie" to "AU",
        "allemagne" to "DE",
        "angleterre" to "GB",
        "autriche" to "AT",
        "belgique" to "BE",
        "bresil" to "BR",
        "chine" to "CN",
        "coree" to "KR",
        "danemark" to "DK",
        "espagne" to "ES",
        "etats_unis" to "US",
        "etatsunis" to "US",
        "finlande" to "FI",
        "grece" to "GR",
        "hongrie" to "HU",
        "inde" to "IN",
        "irlande" to "IE",
        "islande" to "IS",
        "italie" to "IT",
        "japon" to "JP",
        "mexique" to "MX",
        "norvege" to "NO",
        "nouvelle_zelande" to "NZ",
        "pays_bas" to "NL",
        "paysbas" to "NL",
        "pologne" to "PL",
        "roumanie" to "RO",
        "royaume_uni" to "GB",
        "royaumeuni" to "GB",
        "russie" to "RU",
        "suede" to "SE",
        "suisse" to "CH",
        "tchecoslovaquie" to "CS",
        "tchequie" to "CZ",
        "turquie" to "TR",

        // Special territories and regions
        "tristan_da_cunha" to "SH",
        "saint_helena" to "SH",
        "ascension_island" to "SH",
        "falkland_islands" to "FK",
        "south_georgia_and_the_south_sandwich_islands" to "GS",
        "british_virgin_islands" to "VG",
        "us_virgin_islands" to "VI",
        "cayman_islands" to "KY",
        "turks_and_caicos_islands" to "TC",
        "british_indian_ocean_territory" to "IO",
        "pitcairn_islands" to "PN",
        "isle_of_man" to "IM",
        "jersey" to "JE",
        "guernsey" to "GG",
        "gibraltar" to "GI",
        "bermuda" to "BM",
        "montserrat" to "MS",
        "anguilla" to "AI",
        "cook_islands" to "CK",
        "niue" to "NU",
        "tokelau" to "TK",
        "norfolk_island" to "NF",
        "christmas_island" to "CX",
        "cocos_islands" to "CC",
        "heard_island" to "HM",
        "french_polynesia" to "PF",
        "new_caledonia" to "NC",
        "wallis_and_futuna" to "WF",
        "french_southern_territories" to "TF",
        "saint_pierre_and_miquelon" to "PM",
        "mayotte" to "YT",
        "reunion" to "RE",
        "martinique" to "MQ",
        "guadeloupe" to "GP",
        "french_guiana" to "GF",
        "aruba" to "AW",
        "curacao" to "CW",
        "sint_maarten" to "SX",
        "bonaire" to "BQ",
        "caribbean_netherlands" to "BQ",
        "greenland" to "GL",
        "faroe_islands" to "FO",
        "aland_islands" to "AX",
        "svalbard" to "SJ",
        "jan_mayen" to "SJ",
        "hong_kong" to "HK",
        "macau" to "MO",
        "taiwan" to "TW",
        "puerto_rico" to "PR",
        "guam" to "GU",
        "american_samoa" to "AS",
        "northern_mariana_islands" to "MP",

        // Countries with common alternate names
        "united_states" to "US",
        "united_kingdom" to "GB",
        "great_britain" to "GB",
        "england" to "GB",
        "scotland" to "GB",
        "wales" to "GB",
        "northern_ireland" to "GB",
        "russia" to "RU",
        "russian_federation" to "RU",
        "soviet_union" to "SU",
        "ussr" to "SU",
        "china" to "CN",
        "peoples_republic_of_china" to "CN",
        "south_korea" to "KR",
        "korea_south" to "KR",
        "north_korea" to "KP",
        "korea_north" to "KP",
        "germany" to "DE",
        "west_germany" to "DE",
        "east_germany" to "DD",
        "france" to "FR",
        "italy" to "IT",
        "spain" to "ES",
        "portugal" to "PT",
        "netherlands" to "NL",
        "belgium" to "BE",
        "luxembourg" to "LU",
        "switzerland" to "CH",
        "austria" to "AT",
        "ireland" to "IE",
        "greece" to "GR",
        "turkey" to "TR",
        "poland" to "PL",
        "czech_republic" to "CZ",
        "czechia" to "CZ",
        "czechoslovakia" to "CS",
        "slovakia" to "SK",
        "hungary" to "HU",
        "romania" to "RO",
        "bulgaria" to "BG",
        "yugoslavia" to "YU",
        "serbia" to "RS",
        "croatia" to "HR",
        "slovenia" to "SI",
        "bosnia_and_herzegovina" to "BA",
        "montenegro" to "ME",
        "north_macedonia" to "MK",
        "macedonia" to "MK",
        "kosovo" to "XK",
        "albania" to "AL",
        "ukraine" to "UA",
        "belarus" to "BY",
        "moldova" to "MD",
        "lithuania" to "LT",
        "latvia" to "LV",
        "estonia" to "EE",
        "finland" to "FI",
        "sweden" to "SE",
        "norway" to "NO",
        "denmark" to "DK",
        "iceland" to "IS",
        "canada" to "CA",
        "mexico" to "MX",
        "brazil" to "BR",
        "argentina" to "AR",
        "chile" to "CL",
        "peru" to "PE",
        "colombia" to "CO",
        "venezuela" to "VE",
        "ecuador" to "EC",
        "bolivia" to "BO",
        "paraguay" to "PY",
        "uruguay" to "UY",
        "australia" to "AU",
        "new_zealand" to "NZ",
        "japan" to "JP",
        "india" to "IN",
        "pakistan" to "PK",
        "bangladesh" to "BD",
        "sri_lanka" to "LK",
        "nepal" to "NP",
        "bhutan" to "BT",
        "maldives" to "MV",
        "thailand" to "TH",
        "vietnam" to "VN",
        "cambodia" to "KH",
        "laos" to "LA",
        "myanmar" to "MM",
        "burma" to "MM",
        "malaysia" to "MY",
        "singapore" to "SG",
        "indonesia" to "ID",
        "philippines" to "PH",
        "brunei" to "BN",
        "east_timor" to "TL",
        "timor_leste" to "TL",
        "mongolia" to "MN",
        "kazakhstan" to "KZ",
        "uzbekistan" to "UZ",
        "turkmenistan" to "TM",
        "tajikistan" to "TJ",
        "kyrgyzstan" to "KG",
        "afghanistan" to "AF",
        "iran" to "IR",
        "iraq" to "IQ",
        "syria" to "SY",
        "lebanon" to "LB",
        "jordan" to "JO",
        "israel" to "IL",
        "palestine" to "PS",
        "saudi_arabia" to "SA",
        "united_arab_emirates" to "AE",
        "uae" to "AE",
        "qatar" to "QA",
        "bahrain" to "BH",
        "kuwait" to "KW",
        "oman" to "OM",
        "yemen" to "YE",
        "egypt" to "EG",
        "libya" to "LY",
        "tunisia" to "TN",
        "algeria" to "DZ",
        "morocco" to "MA",
        "sudan" to "SD",
        "south_sudan" to "SS",
        "ethiopia" to "ET",
        "eritrea" to "ER",
        "somalia" to "SO",
        "somaliland" to "SO",
        "djibouti" to "DJ",
        "kenya" to "KE",
        "uganda" to "UG",
        "tanzania" to "TZ",
        "rwanda" to "RW",
        "burundi" to "BI",
        "democratic_republic_of_the_congo" to "CD",
        "congo_kinshasa" to "CD",
        "zaire" to "CD",
        "republic_of_the_congo" to "CG",
        "congo_brazzaville" to "CG",
        "central_african_republic" to "CF",
        "chad" to "TD",
        "cameroon" to "CM",
        "nigeria" to "NG",
        "niger" to "NE",
        "mali" to "ML",
        "burkina_faso" to "BF",
        "senegal" to "SN",
        "gambia" to "GM",
        "guinea" to "GN",
        "guinea_bissau" to "GW",
        "sierra_leone" to "SL",
        "liberia" to "LR",
        "ivory_coast" to "CI",
        "cote_divoire" to "CI",
        "ghana" to "GH",
        "togo" to "TG",
        "benin" to "BJ",
        "gabon" to "GA",
        "equatorial_guinea" to "GQ",
        "sao_tome_and_principe" to "ST",
        "angola" to "AO",
        "zambia" to "ZM",
        "zimbabwe" to "ZW",
        "rhodesia" to "ZW",
        "malawi" to "MW",
        "mozambique" to "MZ",
        "botswana" to "BW",
        "namibia" to "NA",
        "south_africa" to "ZA",
        "lesotho" to "LS",
        "eswatini" to "SZ",
        "swaziland" to "SZ",
        "madagascar" to "MG",
        "mauritius" to "MU",
        "seychelles" to "SC",
        "comoros" to "KM",
        "cape_verde" to "CV",
        "cuba" to "CU",
        "haiti" to "HT",
        "dominican_republic" to "DO",
        "jamaica" to "JM",
        "bahamas" to "BS",
        "barbados" to "BB",
        "trinidad_and_tobago" to "TT",
        "grenada" to "GD",
        "saint_lucia" to "LC",
        "saint_vincent_and_the_grenadines" to "VC",
        "dominica" to "DM",
        "antigua_and_barbuda" to "AG",
        "saint_kitts_and_nevis" to "KN",
        "belize" to "BZ",
        "guatemala" to "GT",
        "honduras" to "HN",
        "el_salvador" to "SV",
        "nicaragua" to "NI",
        "costa_rica" to "CR",
        "panama" to "PA",
        "guyana" to "GY",
        "suriname" to "SR",
        "fiji" to "FJ",
        "papua_new_guinea" to "PG",
        "solomon_islands" to "SB",
        "vanuatu" to "VU",
        "samoa" to "WS",
        "tonga" to "TO",
        "kiribati" to "KI",
        "marshall_islands" to "MH",
        "micronesia" to "FM",
        "palau" to "PW",
        "nauru" to "NR",
        "tuvalu" to "TV",

        // European Union special
        "european_union" to "EU",
        "euro_area" to "EU",
        "eurozone" to "EU"
    )

    fun toIsoCode(numistaIssuerCode: String?): String? {
        if (numistaIssuerCode.isNullOrBlank()) return null

        val normalized = numistaIssuerCode.lowercase().trim()

        // If it's already a 2-letter code, return it uppercase
        if (normalized.length == 2 && normalized.all { it.isLetter() }) {
            return normalized.uppercase()
        }

        // Look up in mapping
        NUMISTA_TO_ISO[normalized]?.let { return it }

        // Try removing underscores and matching
        val withoutUnderscores = normalized.replace("_", "")
        NUMISTA_TO_ISO.entries.firstOrNull { (key, _) ->
            key.replace("_", "") == withoutUnderscores
        }?.let { return it.value }

        return null
    }
}
